apiVersion: apps/v1
kind: Deployment
metadata:
  name: testmain-app
spec:
  replicas: 1 # Solo una réplica en dev
  template:
    spec:
      containers:
      - name: testmain
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/dev_database?useSSL=false"
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: LOGGING_LEVEL_ROOT
          value: "DEBUG"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
