apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

# Resources to include
resources:
  - namespace.yaml
  - ../../base
  - mysql-pv.yaml
  - mysql-pvc.yaml

images:
  - name: ghcr.io/brunoredolfi/testmain
    newTag: dev-76b39d1f2ae67ddcffb0c9d072a6b4b5ab601b0a
# Patches for dev environment
patches:
  # Update PVC reference in MySQL deployment
  - target:
      kind: Deployment
      name: mysql
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: mysql-pvc-dev
