apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "dev_database"  # Dev-specific DB name
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc  # References the base PVC
      # Optional: Init container to ensure directory exists
      initContainers:
      - name: ensure-mysql-dir
        image: busybox
        command: ["mkdir", "-p", "/var/lib/mysql"]
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
