apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-dev
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi  # Smaller for dev
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql-dev
    type: DirectoryOrCreate
