apiVersion: v1
kind: Service
metadata:
  name: testmain-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80         # Puerto estándar del service
    targetPort: 9000 # Puerto de tu app (confirmado en application.properties)
    protocol: TCP
