apiVersion: apps/v1
kind: Deployment
metadata:
  name: testmain-app
spec:
  replicas: 3  # Tres réplicas para HA
  template:
    spec:
      containers:
      - name: testmain
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        # Ejemplo de configuración adicional para prod:
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
