apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testmain-prod

resources:
  - ../../base
  - namespace.yaml
  - mysql-pvc.yaml

patchesStrategicMerge:
  - mysql-deployment-patch.yaml
  - app-deployment-patch.yaml
  - service-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=prod

images:
  - name: ghcr.io/brunoredolfi/testmain
    newTag: prod-d1bce2df208bed29f4c81d52a069854aa5399133
