apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testmain-prod

resources:
  - ../../base
  - namespace.yaml
  - mysql-pvc.yaml

patchesStrategicMerge:
  - mysql-deployment-patch.yaml
  - app-deployment-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=prod

images:
  - name: ghcr.io/brunoredolfi/testmain
    newTag: prod-b93cb2727f2be673097c8e46f55efdadb7f72b52
