apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: testmain-prod

patchesStrategicMerge:
- app-patch.yaml
- service-patch.yaml
- namespace-patch.yaml
- mysql-patch.yaml  # Config especial para GKE

images:
- name: ghcr.io/brunoredolfi/testmain
  newTag: prod
