apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-prod  # PVC diferente para prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-prod
  namespace: testmain-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Más espacio en prod
  storageClassName: standard-rwo  # Usa el StorageClass de GKE
