apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-placeholder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-rwo  # Clase de storage de GKE
