apiVersion: v1
kind: Service
metadata:
  name: testmain-service
spec:
  type: LoadBalancer  # Para GKE/GCP
  # Opcional: Anotaciones para el LB (ej: SSL, health checks)
  annotations:
    cloud.google.com/load-balancer-type: "external"
