apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_PROFILES_ACTIVE: "default"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/testdb?useSSL=false"
  # Las configs específicas de cada entorno van en los overlays
