apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-configmap.yaml
  - app-deployment.yaml
  - db-secret.yaml
  - mysql-deployment.yaml
  - mysql-init-configmap.yaml
  - mysql-service.yaml
  - testmain-service.yaml
