apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- app-configmap.yaml
- db-secret.yaml
- app-deployment.yaml
- testmain-service.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- mysql-pvc.yaml
- mysql-pv.yaml  # Solo para Minikube

# Namespace común (será sobrescrito por overlays)
namespace: testmain-dev  # Valor por defecto, pero los overlays lo cambiarán

commonLabels:
  app: testmain
  tier: backend
