apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- app-configmap.yaml
- db-secret.yaml
- app-deployment.yaml
- testmain-service.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- mysql-pvc.yaml
- mysql-config.yaml         # Added
- mysql-init-script.yaml    # Added

labels:
- includeSelectors: true
  pairs:
    app: testmain
    tier: backend
