apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: testdb
            - name: MYSQL_USER
              value: testuser
            - name: MYSQL_PASSWORD
              value: testpass
          ports:
            - containerPort: 3306
