apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: testmain-dev  # Important for ArgoCD!
spec:
  storageClassName: standard  # ← Minikube's default StorageClass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
