apiVersion: v1
kind: Service
metadata:
  name: testmain
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    app: testmain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
