apiVersion: v1
kind: Service
metadata:
  name: testmain-service
  labels:
    app: testmain
    tier: backend
spec:
  type: NodePort
  selector:
    app: testmain
    tier: backend
  ports:
  - name: http
    port: 80
    targetPort: 9000
    protocol: TCP
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
